### ISSUE TITLE
Default theme and accent color not work as expected

### ISSUE THREAD

**Issue by GF-Huang** [Kinnara/ModernWpf#147] opened 2020-07-25 00:13 UTC
![image](https://user-images.githubusercontent.com/4510984/88444161-55c58380-ce4e-11ea-9c19-6386a8c2b834.png)

App looks:

![image](https://user-images.githubusercontent.com/4510984/88444220-b0f77600-ce4e-11ea-87a6-de0e95bad464.png)

My system accent:

![image](https://user-images.githubusercontent.com/4510984/88444171-5fe78200-ce4e-11ea-9931-370032c26ad6.png)

Is this earlier?

![image](https://user-images.githubusercontent.com/4510984/88444184-71308e80-ce4e-11ea-879a-30d900d0e7c8.png)

**Comment by ShankarBUS** [comment] 2020-07-25 05:04
See #143, this is a duplicate of that issue.

**Comment by GF-Huang** [comment] 2020-07-25 08:03
OK, should I close this issue or leave for new users?

**Comment by ShankarBUS** [comment] 2020-07-25 08:07
Closing this would be fine since it reduced the no. of open issues and will help tracking and fixing them

**Closed** 2020-07-25 08:07 UTC
