### ISSUE TITLE
[Feature Request] Color Picker

### ISSUE THREAD

**Issue by Astyr6** [Kinnara/ModernWpf#120] opened 2020-06-22 16:11 UTC
Hey, I higly appreciate your work and use it, but would it be possible to have a color picker similar to the one in XAML Controls Gallery App.

![ApplicationFrameHost_xJLAZdF9GQ](https://user-images.githubusercontent.com/66996108/85309889-8adb6080-b4b3-11ea-8e33-a2d9c213f285.png)
https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.colorpicker?view=winui-2.4

Best regards,
Astyr

**Comment by ShankarBUS** [comment] 2020-06-22 16:19
Duplicate of #72.

**Comment by Astyr6** [comment] 2020-06-22 17:44
Oh sorry

**Closed** 2020-06-22 17:44 UTC
