### ISSUE TITLE
Window is all black in classlibrary project

### ISSUE THREAD

**Issue by sherlockforrest** [Kinnara/ModernWpf#97] opened 2020-05-16 03:48 UTC
Control is initialized, but not visible

**Comment by ShankarBUS** [comment] 2020-06-09 14:28
It may be due to the resources and styles not being available in the class library.
Since a _class library_ project doesn't have the **Application** class i.e. **App.xaml**, the styles for the window won't be available.

You have 2 options

1. You can add this ⬇️ in to **App.xaml** in your **Main executing project** (the one that produces a *.exe)
```xaml
<Application
    ...
    xmlns:ui="http://schemas.modernwpf.com/2019">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```
2. Or if the window has a xaml file add this to it
```xaml
<Window
    ...
    xmlns:ui="http://schemas.modernwpf.com/2019"
    ui:WindowHelper.UseModernWindowStyle="True">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
</Window>
```

If these don't work, can you share any repro of your window's xaml or code?

**Comment by sherlockforrest** [comment] 2020-06-11 08:45
I use this for Autodesk Revit development, and I use it the way you say it, but it doesn't work, and you need to install Autodesk Revit to test this problem, which is very cumbersome. The window looks like this
![20200611164346](https://user-images.githubusercontent.com/40654941/84364550-cbf58a00-ac02-11ea-9435-550d471f22cc.png)

**Comment by sherlockforrest** [comment] 2020-06-11 08:53
https://github.com/sherlockforrest/CLSample

**Comment by ShankarBUS** [comment] 2020-06-11 11:09
Ok, did you try creating the window from another executable project? If it didn't happen there it must be a problem with Revit

**Comment by Kinnara** [comment] 2020-06-11 17:36
This can get complicated. I'll try to come up with a solution over the weekend.

**Comment by Kinnara** [comment] 2020-06-17 17:46
The issue is merging `ThemeResources` into a window won't work properly; it has to be merged into app resources. I know nothing about Autodesk Revit, but for a Word VSTO add-in you can add a method:
```cs
public static void EnsureApplicationResources()
{
    if (Application.Current is null)
    {
        var app = new Application { ShutdownMode = ShutdownMode.OnExplicitShutdown };

        var themeResources = new ThemeResources();
        themeResources.BeginInit();
        app.Resources.MergedDictionaries.Add(themeResources);
        themeResources.EndInit();

        app.Resources.MergedDictionaries.Add(new XamlControlsResources());
    }
}
```
and call it before showing the window (e.g. before `InitializeComponent`). Then call `Application.Current?.Shutdown()` when your program shuts down.

**Comment by sherlockforrest** [comment] 2020-06-18 04:08
Ok,I will try it,thank you very much.

**Comment by sherlockforrest** [comment] 2020-06-19 09:49
Sorry, it doesn't work, I use other WPF control libraries, like HandyControls and MahApps.Metro, and there's no such problem.Thank you for your time.

**Comment by AlonAm** [comment] 2020-09-27 12:06
> 
> 
> The issue is merging `ThemeResources` into a window won't work properly; it has to be merged into app resources. I know nothing about Autodesk Revit, but for a Word VSTO add-in you can add a method:
> 
> ```cs
> public static void EnsureApplicationResources()
> {
>     if (Application.Current is null)
>     {
>         var app = new Application { ShutdownMode = ShutdownMode.OnExplicitShutdown };
> 
>         var themeResources = new ThemeResources();
>         themeResources.BeginInit();
>         app.Resources.MergedDictionaries.Add(themeResources);
>         themeResources.EndInit();
> 
>         app.Resources.MergedDictionaries.Add(new XamlControlsResources());
>     }
> }
> ```
> 
> and call it before showing the window (e.g. before `InitializeComponent`). Then call `Application.Current?.Shutdown()` when your program shuts down.

Thank you!

**Closed** 2022-02-28 16:42 UTC
Labels: discussion
