### ISSUE TITLE
"System.Windows.ResourceDictionary Warning: 9 : Resource not found" when changing themes

### ISSUE THREAD

**Issue by Coke21** [Kinnara/ModernWpf#29] opened 2020-01-30 15:22 UTC
Hi, I'm using 0.8 ModernWpf and 0.8 MahApps and for some reason every time I change themes I get spammed "System.Windows.ResourceDictionary Warning: 9 : Resource not found".
This is my View:
```
                    <ui:RadioButtons SelectedIndex="{Binding SelectedThemeIndex, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
                        <ui:RadioButtons.Header>
                            <StackPanel Orientation="Horizontal">
                                <iconPacks:PackIconMaterial Kind="ThemeLightDark" VerticalAlignment="Center"/>
                                <Label Content="Theme Mode" Margin="2 0 0 0"/>
                            </StackPanel>
                        </ui:RadioButtons.Header>

                        <system:String>Light</system:String>
                        <system:String>Dark</system:String>
                    </ui:RadioButtons>
```
ViewModel:
```
        private int _selectedThemeIndex;
        public int SelectedThemeIndex
        {
            get { return _selectedThemeIndex; }
            set
            {
                _selectedThemeIndex = value;

                ThemeManager.Current.ApplicationTheme = SelectedThemeIndex switch
                {
                    0 => ApplicationTheme.Light,
                    1 => ApplicationTheme.Dark
                };

                NotifyOfPropertyChange(() => SelectedThemeIndex);
            }
        }
```
App.xaml:
```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <local:Bootstrapper x:Key="Bootstrapper"/>
                </ResourceDictionary>

                <ui:ThemeResources />
                <ui:XamlControlsResources />

                <ui:ThemeResources>
                    <ui:ThemeResources.ThemeDictionaries>
                        <ResourceDictionary x:Key="Light">
                            <ResourceDictionary.MergedDictionaries>
                                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
                            </ResourceDictionary.MergedDictionaries>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="Dark">
                            <ResourceDictionary.MergedDictionaries>
                                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Themes/Dark.Blue.xaml" />
                            </ResourceDictionary.MergedDictionaries>
                        </ResourceDictionary>
                    </ui:ThemeResources.ThemeDictionaries>
                </ui:ThemeResources>

                <ui:MahAppsColorPaletteResources />
                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Fonts.xaml" />

                <ui:XamlControlsResources />
                <ResourceDictionary Source="/ModernWpf.MahApps;component/Styles/Controls.xaml" />

            </ResourceDictionary.MergedDictionaries>

        </ResourceDictionary>
    </Application.Resources>
```
When I change themes my app freezes for like 2 seconds and then I get spammed with the above warning and the theme changes. I don't know what's wrong here.

**Comment by Kinnara** [comment] 2020-01-31 12:28
Thanks for the report. There's nothing wrong with your code. The warnings are caused by code changes in 0.8, and will be fixed in the next version. While the warnings make debugging slower, the app should run fine.

**Comment by Coke21** [comment] 2020-01-31 22:28
Thank you for quick help. I have one more question. I'm trying to use your `ui:NumberBox` instead of MahApps' `mah:NumericUpDown` The second control had TextAlignment property which was really useful, can I somehow align text with your control?

**Comment by Kinnara** [comment] 2020-02-01 15:40
The TextAlignment property will eventually be added according to [the proposal](https://github.com/microsoft/microsoft-ui-xaml/issues/1736). Before that happens, you can use the following:
```cs
public class NumberBoxEx : NumberBox
{
    public static readonly DependencyProperty TextAlignmentProperty = Block.TextAlignmentProperty.AddOwner(typeof(NumberBoxEx));

    public TextAlignment TextAlignment
    {
        get => (TextAlignment)GetValue(TextAlignmentProperty);
        set => SetValue(TextAlignmentProperty, value);
    }

    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();

        if (GetTemplateChild("InputBox") is TextBox textBox)
        {
            textBox.SetBinding(TextBox.TextAlignmentProperty,
                new Binding
                {
                    Path = new PropertyPath(TextAlignmentProperty),
                    RelativeSource = RelativeSource.TemplatedParent
                });
        }
    }
}
```

**Closed** 2020-02-07 03:27 UTC
