### ISSUE TITLE
.Net Core 5.0 not support WinRT

### ISSUE THREAD

**Issue by TaylorShi** [Kinnara/ModernWpf#407] opened 2021-10-30 08:28 UTC
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NETSDK1149	无法引用 ModernWpf.dll，因为它使用了对 WinRT 的内置支持，而 .NET 5 和更高版本中不再支持它。需要支持 .NET 5 的更新版本组件。有关详细信息，请参阅 https://aka.ms/netsdk1149	demoForWpfCore	C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1003	

Previously, CoreCLR could consume Windows metadata (WinMD) files to active and consume WinRT types. Starting in .NET 5, CoreCLR can no longer consume WinMD files directly.

If you attempt to reference an unsupported assembly, you'll get a FileNotFoundException. If you activate a WinRT class, you'll get a PlatformNotSupportedException.

This breaking change was made for the following reasons:

So WinRT can be developed and improved separately from the .NET runtime.
For symmetry with interop systems provided for other operating systems, such as iOS and Android.
To take advantage of other .NET features, such as C# features, intermediate language (IL) trimming, and ahead-of-time (AOT) compilation.
To simplify the .NET runtime codebase.

**Comment by BobbyESP** [comment] 2021-11-05 19:58
Same

**Comment by andrescirulo** [comment] 2021-11-14 16:05
I have the same problem, but I think the title of the issue can be missleading. The path to your sdk says "6.0.100" which means it's .NET Core 6.0.
I have no problem running my app with .Net Core 5.0, but when I upgraded to 6.0 I started getting this problem. 
If I understand correctly, the issue with 5.0 was solved in version 0.9.2 in the commit named "Multitargeting updates". Maybe there is something that has to be done to add support to 6.0

**Comment by BieleckiLtd** [comment] 2021-12-07 17:04
Is there a workaround to make ModernWPF working on .NET 6?

**Comment by myangelkamikaze** [comment] 2021-12-20 17:36
This should be a duplicate of https://github.com/Kinnara/ModernWpf/issues/307.
Set the target framework to ```net6.0-windows10.0.18362.0``` and it should work.

**Comment by msbrunoalves** [comment] 2021-12-27 11:25
> This should be a duplicate of #307. Set the target framework to `net6.0-windows10.0.18362.0` and it should work.

Can confirm this works, thank you.

**Comment by xiaoniu1234** [comment] 2022-04-05 02:44
You can try to install the nuget package "Microsoft.Windows.CsWinRT"

**Comment by Kinnara** [comment] 2022-05-29 18:32
Resolved by #451.

**Closed by Kinnara** 2022-05-29 18:32 UTC
Labels: needs-triage
