### ISSUE TITLE
[Bug] Accent Color and System Theme changes are not updated in Packaged WPF apps

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#175] opened 2020-09-17 07:09 UTC
This could be similar to #143. But this is an entirely different case.

There was an attempt to remove the `app.manifest` requirement (previously a mandatory need to detect the OS version) in 2c27fba92296ff54bde425fb7d3bd1baa844eb86. Despite removing the `app.manifest` requirement the bug has occurred to me (and I do have app manifest)

When the app is executed as an unpackaged application, there are no problems with theme/accent changes.
But when the same app is executed as a packaged (MSIX) application, the accent-color/system-theme changes are not perceived by the packaged application.

I can assure that this bug doesn't happen when the app is unpackaged.

**Workaround**

~~I used **Reflection** to invoke this internal method~~ This won't work see https://github.com/Kinnara/ModernWpf/issues/175#issuecomment-701740907

```cs
private void ListenToSystemColorChanges()
{
    Type ColorsHelperType = Type.GetType("ModernWpf.ColorsHelper, ModernWpf");
    PropertyInfo CurrentProperty = ColorsHelperType.GetProperty("Current", BindingFlags.Static | BindingFlags.Public);
    object colorsHelperInstance = CurrentProperty.GetValue(null);
    MethodInfo ListenToSystemColorChangesMethod = ColorsHelperType.GetMethod("ListenToSystemColorChanges",
        BindingFlags.Instance | BindingFlags.NonPublic);
    ListenToSystemColorChangesMethod.Invoke(colorsHelperInstance, null);
}
```

**Comment by Kinnara** [comment] 2020-09-25 16:56
Thanks for reporting. I'll look into it.

**Comment by Kinnara** [comment] 2020-09-29 18:44
The cause seems to be `UISettings` doesn't raise any events in a packaged app, although its methods and properties work fine. Does the workaround actually work? `ListenToSystemColorChanges` is already called inside the library and calling it again shouldn't make any difference.

**Comment by ShankarBUS** [comment] 2020-09-30 01:07
Yep, calling it works. I'm really confused now. I don't know how the workaround actually worked 😅

How can `UISettings` not fire events?  We already use some other WinRT APIs in our app and all of them (except one event) work fine.

You can clone the `ModernFlyouts` repo and check it out yourself.

I thought there were problems with the **OSVersionHelper** & packaging.
So I manually called the `ListenToSystemColorChanges` method myself. It worked however. Are you sure `UISettings` is the problem here?

**Comment by Kinnara** [comment] 2020-09-30 16:59
Yes, I'm fairly certain `UISettings` is the culprit, at least on Win10 2004. I tried ModernFlyouts and calling `ListenToSystemColorChanges` didn't seem to help—the settings window still didn't react to theme changes, for example.

**Comment by ShankarBUS** [comment] 2020-09-30 17:08
Weird!!! There seems to be many issues with WinRT event triggering in .NET. Even an important API our app depends on (GSMTC) has this same problem. What should we do then?

How does the API work fine on unpackaged apps then?
It only happened while it was packaged. I thought the version checking didn't work but this seems to be out of our expertise, right?

Side note: I'm 100% that it works fine if call the method using reflection. I remember it working fine. So I disagree with you.

I will report to you in details tomorrow morning

**Comment by ShankarBUS** [comment] 2020-10-01 01:38
Yep! It's what you say 😅.

**Comment by ShankarBUS** [comment] 2020-10-01 01:51
I guess I will need to do another workaround
- Hook to registry changes (use WMI event watcher to watch changes in the reg key - **"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize"**'s value **"AppsUseLightTheme"** for theme changes)
- Handle window messages (i.e. **WM_DWMCOLORIZATIONCOLORCHANGED** for accent colour changes)

I already have a method to watch **"SystemUsesLightTheme"** so it will be relatively easy for me to workaround this until you find a way to fix this. (**Referrence : [SystemTheme.cs](https://github.com/ShankarBUS/ModernFlyouts/blob/master/ModernFlyouts/SystemTheme.cs)**)

**Comment by Kinnara** [comment] 2020-10-03 16:58
Fixed by 57b71b4.

**Closed** 2020-10-03 16:58 UTC
Labels: bug

**Comment by ShankarBUS** [comment] 2020-10-04 01:26
Thanks @Kinnara!

**Comment by ShankarBUS** [comment] 2020-10-04 13:49
Hey @Kinnara, a suggestion

While committing a fix regarding a issue, you can use the  `Fix\Fixed\Fixes #{issue-no} {Issue Title}` format to automatically close those issues while committing.

It saves me a lot of time. Would be helpful for you maintaining a repo efficiently

**Comment by ShankarBUS** [comment] 2020-10-17 12:06
@Kinnara, this bug is still not fixed.
https://github.com/ShankarBUS/ModernFlyouts/issues/38#issuecomment-709409549
I verified it myself. It still happens 😞
The app once published doesn't respond to system theme changes. I will have to go with my workaround - https://github.com/Kinnara/ModernWpf/issues/175#issuecomment-701740907
